### ISSUE TITLE
Problem with TwoFaQr::widget

### ISSUE THREAD

**Issue by saschahaendle** [promocat/yii2-twofa#1]
Hello,

i became the error 'Undefined array key "twoFaIssuer"' when i use TwoFaQr::widget in 'site/login-verification'

php

use promocat\twofa\widgets\TwoFaQr;

TwoFaQr::widget([
    'accountName' => $model->user->username,
    'secret' => $model->secret,
    'issuer' => Yii::$app->params['twoFaIssuer'],
    'size' => 300
]);

Can anybody help me please?

I think I need to add a corresponding entry in config/params.php. But what content must this entry have?

**Comment by C4RoCKeT** [comment]
You should define 'twoFaIssuer' in the params file or just use a string
with the issuer name.

Op vr 29 jul. 2022 10:21 schreef Sascha Händle ***@***.***>:

**Comment by saschahaendle** [comment]
Thank you. I fixed the problem. It works now fine.
