### ISSUE TITLE
Examples for pages 'enable-two-fa', 'login-verification'

### ISSUE THREAD

**Issue by nazbav** [promocat/yii2-twofa#3]
Please publish examples for templates 'enable-two-fa', 'login-verification'

**Comment by BrandonTilstra** [comment]
I've added an "examples" folder and removed the old `examples.php`.
This is the best I could do. This is meant to be a barebones package that should be implemented into a working authentication process. 
The `enable-two-fa` and `login-verifcation` views should be heavily modified and should just be seen als "inspiration".

Security wise, I recommend also validating the users current password when enabling/disabling 2FA for a user. This is something you should implement yourself.

**Comment by nazbav** [comment]
Thx!

But messages category "twofa" in  ```Yii:t("twofa",...)``` it is not provided together with the extension?
